apiVersion: apps/v1
kind: Deployment
metadata:
  name: ans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ans
  template:
    metadata:
      labels:
        app: ans
    spec:
      containers:
        - name: ans
          image: akanork/dhmas-newest-ans
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: ans
spec:
  selector:
    app: ans
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
