apiVersion: apps/v1
kind: Deployment
metadata:
  name: has
spec:
  replicas: 1
  selector:
    matchLabels:
      app: has
  template:
    metadata:
      labels:
        app: has
    spec:
      containers:
        - name: has
          image: akanork/dhmas-newest-has
