apiVersion: apps/v1
kind: Deployment
metadata:
  name: oximeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oximeter
  template:
    metadata:
      labels:
        app: oximeter
    spec:
      containers:
        - name: oximeter
          image: akanork/dhmas-newest-oximeter
