apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pms
  template:
    metadata:
      labels:
        app: pms
    spec:
      containers:
        - name: pms
          image: akanork/dhmas-newest-pms
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: pms
spec:
  selector:
    app: pms
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
