apiVersion: apps/v1
kind: Deployment
metadata:
  name: respirometer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: respirometer
  template:
    metadata:
      labels:
        app: respirometer
    spec:
      containers:
        - name: respirometer
          image: akanork/dhmas-newest-respirometer
