apiVersion: apps/v1
kind: Deployment
metadata:
  name: thermometer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thermometer
  template:
    metadata:
      labels:
        app: thermometer
    spec:
      containers:
        - name: thermometer
          image: akanork/dhmas-newest-thermometer
